name: deploy to Heroku
on:
  push:
    branches:
      - main
  # for debug
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/deploy_to_heroku.yml

jobs:
  build-and-push:
    name: build and push
    runs-on: ubuntu-latest
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Heroku Container Registry
      uses: docker/login-action@v1
      with:
        registry: registry.heroku.com
        username: ${{ secrets.heroku_username }}
        password: ${{ secrets.heroku_password }}

    - name: Push to Heroku Container Registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: registry.heroku.com/gslide-presen-share/web
        context: ./gcp/page_sync_backend
