name: deploy to Heroku
on:
  push:
    branches:
      - main
  # for debug
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/deploy_to_heroku.yml

jobs:
  build-and-push:
    name: build and push
    runs-on: ubuntu-latest
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Heroku Container Registry
      uses: docker/login-action@v1
      with:
        registry: registry.heroku.com
        username: ${{ secrets.HEROKU_USERNAME }}
        password: ${{ secrets.HEROKU_PASSWORD }}

          #    - name: Prepare Heroku login credentials
          #      run: |
          #        cat > ~/.netrc <<EOF
          #          machine api.heroku.com
          #            login $HEROKU_EMAIL
          #            password $HEROKU_API_KEY
          #          machine git.heroku.com
          #            login $HEROKU_EMAIL
          #            password $HEROKU_API_KEY
          #        EOF
          #      env:
          #        HEROKU_EMAIL: ${{ secrets.HEROKU_USERNAME }}
          #        HEROKU_API_KEY: ${{ secrets.HEROKU_PASSWORD }}

    - name: Push to Heroku Container Registry
      run: |
        heroku container:push -a=gslide-presen-share web
      working-directory: gcp/page_sync_backend

    - name: Release pushed container
      run: |
        heroku container:release --app=${{ secrets.HEROKU_APPNAME }} web
      working-directory: gcp/page_sync_backend
