name: deploy to Heroku
on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/deply_to_heroku.yml'

jobs:
  build-and-push:
    name: build and push
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Prepare Heroku login credentials
      run: |
        cat > ~/.netrc <<EOF
          machine api.heroku.com
            login $HEROKU_EMAIL
            password $HEROKU_API_KEY
          machine git.heroku.com
            login $HEROKU_EMAIL
            password $HEROKU_API_KEY
        EOF
      env:
        HEROKU_EMAIL: ${{ secrets.HEROKU_USERNAME }}
        HEROKU_API_KEY: ${{ secrets.HEROKU_PASSWORD }}

    - name: Login to Heroku Container Registry
      run: |
        heroku container:login

    - name: Push to Heroku Container Registry
      run: |
        heroku container:push --app ${{ secrets.HEROKU_APPNAME }} web
      working-directory: backend

    - name: Release pushed container
      run: |
        heroku container:release --app ${{ secrets.HEROKU_APPNAME }} web
      working-directory: backend
